In [64]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [65]:
df = pd.read_csv('covid_toy.csv')

In [66]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

### 1. normal data : fever
### 2. Ordinal columns : cough
### 3. Norminal columns : gender, city

In [69]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [70]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='has_covid'), df['has_covid'], test_size=0.2)

In [71]:
X_train

    age  gender  fever   cough       city
57   49  Female   99.0  Strong  Bangalore
76   80    Male  100.0    Mild  Bangalore
53   83    Male   98.0    Mild      Delhi
83   17  Female  104.0    Mild    Kolkata
39   50  Female  103.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
11   65  Female   98.0    Mild     Mumbai
23   80  Female   98.0    Mild      Delhi
72   83  Female  101.0    Mild    Kolkata
95   12  Female  104.0    Mild  Bangalore
27   33  Female  102.0  Strong      Delhi

[80 rows x 5 columns]

In [78]:
mid = df.fever.median()
df.fever = df.fever.fillna(mid)
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [81]:
df.cough.unique()

array(['Mild', 'Strong'], dtype=object)

In [82]:
df.city.unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'], dtype=object)

### One_Hot_Encoding (for nominal data) and Ordinal_Encoding (for ordinal data) using Column Transform

In [80]:
from sklearn.compose import ColumnTransformer

In [ ]:
# passing 3 Encoder in single columtransformer at ones 

transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False, drop='first'), ['gender', 'city'])
    ],remainder='passthrough')   # reminder : what to do with remaining columns "passthrough", or "drop"